INSERT INTO USERS (FULL_NAME, USERNAME, PASSWORD, IS_ACTIVE)
VALUES ('Admin', 'admin@gmail.com', '$2a$10$PRex3hFH8n.1sZByoZFDhuBvZga.npk2vK4ztvI0pyhCiEFaSTzCG', true);

INSERT INTO ROLES (NAME)
VALUES ('ROLE_ADMIN'),
       ('ROLE_USER');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (1, 1);